/*
 * This Java source file was auto generated by running 'gradle buildInit'
 * by 'Felipe' at '02/04/17 11:22' with Gradle 2.14.1
 *
 * @author Felipe, @date 02/04/17 11:22
 */
import javax.sql.DataSource;

import org.springframework.batch.core.configuration.annotation.DefaultBatchConfigurer;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
@SpringBootApplication
@ComponentScan({"pojo","configuration","listener","reader","processor","writer"})
public class BatchBoot  extends DefaultBatchConfigurer {
	public static void main(String[] args) {
		SpringApplication.run(BatchBoot.class, args);
	}
	
//	@Override
//    public void setDataSource(DataSource dataSource) {
//		dataSource = null;
//        // override to do not set datasource even if a datasource exist.
//        // initialize will use a Map based JobRepository (instead of database)
//    }
//	
//	@Override
//	public JobRepository getJobRepository() {
//		return null;
//	}
}
